name: test_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  intl: ^0.18.1
  wifi_iot: ^0.3.18+1
  connectivity_plus: ^3.0.2
  wifi_scan: ^0.4.0+2
  socket_io_client: ^2.0.3+1
  permission_handler: ^11.0.1
  battery_info: ^1.1.1
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
